Update main.py
feshovets/prog pull request #1
Opened 2021-09-12 12:00 UTC by feshovets

2021-09-16 11:09 UTC, tetianastoyko requested changes

2021-09-16 11:09 UTC, tetianastoyko commented on main.py
> +#review
Жодної валідації в програмі

2021-09-23 16:11 UTC, tetianastoyko reviewed
Не найкраще, але норм

2021-09-24 05:23 UTC, feshovets reviewed
+

2021-09-24 05:34 UTC, merged